### ISSUE TITLE
Run also on PR

### ISSUE THREAD

**Issue by alorma** [dag-io/create-install-page-qr-code-step#1]
Hi.

Recently we noticed that our PR builds were not generating the QR code.

after some research i get this:

```
run_if: .IsCI | and (not .IsPR)
```

Is there any chance to delete the `not .IsPr` ?

We already added on the *bitrise.yml*

```
    - create-install-page-qr-code@0.1.2:
        run_if: true
```
but i don't see any option in the visual configuration step, could you add it pls?

**Comment by BirmacherAkos** [comment]
Hi!

We have released a new version [(1.0.0)](https://github.com/bitrise-steplib/steps-create-install-page-qr-code/releases/tag/1.0.0) Create install page QR code step.

 - It has been rewritten in Golang.
 - Build URL is requeired
 - step.yml clean

And it doesn't contain the 
`run_if: .IsCI | and (not .IsPR)`
